### ISSUE TITLE
wrong versionName?

### ISSUE THREAD

**Issue by IzzySoft** [adityar224/FontGallery#2]
The APK at tag `1.2.0` identifies as

    package: name='com.adeeteya.font_gallery' versionCode='5' versionName='1.1.3'

Is this the correct APK (and you forgot to adjust `versionName`), or was just the wrong APK attached?

**Comment by adityar224** [comment]
Thanks for pointing this out. I have accidentally attached the previous version of the app. I have edited the release to include the newer version 👍.

**Comment by IzzySoft** [comment]
Thanks! But now it looks like you forgot to increase `versionCode`:

```
$ iod repo get com.adeeteya.font_gallery
com.adeeteya.font_gallery: looking for 'https://api.github.com/repos/adityar224/FontGallery/releases'
com.adeeteya.font_gallery: checking tag '1.2.0'
com.adeeteya.font_gallery: lastRelNo set to '1.2.0', checking for files
com.adeeteya.font_gallery: Upstream file date (2023-05-18 20:03) is newer than ours (2023-05-18 14:40).
com.adeeteya.font_gallery: returning ['1.2.0','https://github.com/adityar224/FontGallery/releases/download/1.2.0/FontGallery-Android.apk',1684432982]
com.adeeteya.font_gallery: 1.1.3/1.2.0, https://github.com/adityar224/FontGallery/releases: https://github.com/adityar224/FontGallery/releases/download/1.2.0/FontGallery-Android.apk
- Grabbing update for com.adeeteya.font_gallery: OK
Binary files /web/ftp/repo/fdroid/repo/com.adeeteya.font_gallery_5.apk and /web/ftp/repo/fdroid/repo/com.adeeteya.font_gallery_1.2.0.apk differ
```

This means there won't be any update notifications given to those having it installed.

Oops, background: I've added your app to my repo, so it can be installed from and kept updated via any F-Droid client. You can [find the listing here](https://apt.izzysoft.de/fdroid/index/apk/com.adeeteya.font_gallery). As the app just went live today, I doubt it was already installed by many – so please just take care for future releases with this :wink:

Oh, and if you want you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to that place :smiley:

**Comment by adityar224** [comment]
In version 1.1.3- comparing fonts had a major bug which I quickly found out post commit and was never supposed to be released.
That's why version number wasn't changed. It has changed from the previous play store release tho.

The app went live few months back and yes versionCode shouldn't be a problem. If you had already installed 1.1.3 then I'd suggest uninstalling it.

**Comment by IzzySoft** [comment]
OK, got it. v1.2.0 will replace v1.1.3 anyway due to file naming patterns (`<applicationId>_<versionCode>.apk`) with the next sync.
